<<<<<<< HEAD

index:
    path: /
    controller: App\Controller\SymfonyControler::home
=======
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
>>>>>>> e49b1dfe5b045318f40db073ccb2cd632608db0f
